import type { SeasonId, StyleGuide } from "@photomatcher/types";

/** Original PhotoMatcher style guides — not copied from third-party palette products. */
export const STYLE_GUIDES: Record<SeasonId, StyleGuide> = {
  bright_spring: {
    contrastLevel: "high",
    valueDepth: "medium",
    suits: [
      "Light warm navy or teal suit with clear, not dusty, finish",
      "Warm charcoal with a crisp coral or golden pocket square",
      "Cream or warm ivory suit for summer events",
    ],
    shirtsAndBlouses: [
      "Warm white, peach, or clear aqua dress shirts",
      "Light coral blouses with minimal pattern",
    ],
    tiesAndScarves: [
      "Coral, clear turquoise, or warm golden yellow",
      "Avoid muddy brown or grey-beige ties",
    ],
    casualWear: [
      "Bright coral polos, mint tees, and clear aqua knits",
      "Light denim with warm undertone (not icy blue)",
    ],
    dressesAndSkirts: [
      "Sunny yellow, coral, or clear aqua A-line dresses",
      "White or peach skirts with lively accent tops",
    ],
    denim: ["Medium-wash blue with warm cast", "White or light coral chinos"],
    outerwear: ["Camel with clean lines", "Bright spring green or coral rain jacket"],
    shoesAndBags: ["Warm tan leather", "Coral or teal accent bags"],
    makeup: {
      lips: ["Coral", "Warm rose", "Peach nude"],
      cheeks: ["Peach blush", "Warm apricot"],
      eyes: ["Warm bronze", "Teal liner", "Golden champagne shadow"],
    },
    jewelry: ["Yellow gold", "Warm rose gold", "Coral or turquoise stones"],
    hairColorHints: ["Golden blonde highlights", "Warm copper gloss", "Rich warm brown"],
    patterns: ["Bold florals", "Geometric brights", "Clear stripes"],
    neutrals: ["Warm white", "Light camel", "Warm navy"],
    occasions: [
      { label: "Business", suggestion: "Warm navy suit, peach shirt, coral tie" },
      { label: "Casual", suggestion: "Mint knit, light denim, tan sneakers" },
      { label: "Evening", suggestion: "Coral dress or teal blazer with warm white shirt" },
    ],
  },
  true_spring: {
    contrastLevel: "medium",
    valueDepth: "medium",
    suits: [
      "Warm navy, golden brown, or olive-green suit",
      "Light tan suit for daytime weddings",
    ],
    shirtsAndBlouses: [
      "Ivory, warm peach, or light aqua shirts",
      "Golden-yellow or warm green blouses",
    ],
    tiesAndScarves: ["Golden yellow", "Warm teal", "Clear orange"],
    casualWear: ["Warm green henleys", "Peach and ivory knits", "Khaki chinos"],
    dressesAndSkirts: ["Golden yellow wrap dress", "Warm green or peach midi skirts"],
    denim: ["Classic medium blue denim", "Khaki or olive chinos"],
    outerwear: ["Olive trench", "Warm camel coat"],
    shoesAndBags: ["Cognac leather", "Warm brown loafers"],
    makeup: {
      lips: ["Warm peach", "Sheer orange-red", "Apricot gloss"],
      cheeks: ["Warm peach", "Soft apricot bronzer"],
      eyes: ["Copper", "Warm olive", "Soft gold shadow"],
    },
    jewelry: ["Yellow gold", "Amber", "Warm jade"],
    hairColorHints: ["Honey blonde", "Warm auburn", "Golden brown base"],
    patterns: ["Tropical prints", "Warm botanicals", "Soft gingham in peach or green"],
    neutrals: ["Ivory", "Khaki", "Warm olive"],
    occasions: [
      { label: "Business", suggestion: "Warm navy suit, ivory shirt, golden tie" },
      { label: "Weekend", suggestion: "Olive jacket, peach tee, khaki chinos" },
      { label: "Date night", suggestion: "Warm green dress with gold accessories" },
    ],
  },
  light_spring: {
    contrastLevel: "low",
    valueDepth: "light",
    suits: [
      "Light warm grey or soft beige suit",
      "Pale warm navy for formal events",
    ],
    shirtsAndBlouses: ["Soft ivory", "Peach", "Butter yellow", "Powder aqua"],
    tiesAndScarves: ["Pastel peach", "Soft aqua", "Butter yellow — keep low contrast"],
    casualWear: ["Soft peach knits", "Ivory linen shirts", "Light khaki shorts"],
    dressesAndSkirts: ["Floral pastels in warm undertone", "Ivory lace or chiffon"],
    denim: ["Light wash denim", "Stone or sand chinos"],
    outerwear: ["Soft beige blazer", "Light peach or ivory coat"],
    shoesAndBags: ["Nude or soft tan", "Ivory or blush bags"],
    makeup: {
      lips: ["Peach nude", "Soft coral", "Sheer pink"],
      cheeks: ["Soft peach", "Light apricot"],
      eyes: ["Champagne", "Soft peach shadow", "Brown mascara"],
    },
    jewelry: ["Rose gold", "Light gold", "Pearl with warm undertone"],
    hairColorHints: ["Strawberry blonde", "Soft golden highlights", "Light warm brown"],
    patterns: ["Delicate florals", "Soft watercolor prints", "Thin warm stripes"],
    neutrals: ["Ivory", "Soft beige", "Light warm grey"],
    occasions: [
      { label: "Office", suggestion: "Soft beige suit, peach blouse, nude heels" },
      { label: "Brunch", suggestion: "Ivory linen dress, tan sandals" },
      { label: "Wedding guest", suggestion: "Powder aqua dress, rose gold jewelry" },
    ],
  },
  light_summer: {
    contrastLevel: "low",
    valueDepth: "light",
    suits: [
      "Soft cool grey or dusty blue suit",
      "Light cool navy with minimal contrast",
    ],
    shirtsAndBlouses: ["Soft white", "Powder blue", "Lilac", "Blush pink"],
    tiesAndScarves: ["Lilac", "Powder blue", "Soft rose"],
    casualWear: ["Lavender knits", "Soft blue oxford shirts", "Cool grey chinos"],
    dressesAndSkirts: ["Lilac midi", "Powder blue wrap", "Soft rose tea dress"],
    denim: ["Light cool-wash denim", "Soft grey trousers"],
    outerwear: ["Dusty blue coat", "Soft grey trench"],
    shoesAndBags: ["Soft grey or taupe-cool", "Blush or lilac accent bags"],
    makeup: {
      lips: ["Rose pink", "Soft mauve", "Cool nude"],
      cheeks: ["Cool pink", "Soft rose"],
      eyes: ["Soft grey", "Lilac", "Cool taupe shadow"],
    },
    jewelry: ["Silver", "Cool rose gold", "Soft amethyst"],
    hairColorHints: ["Ash blonde", "Cool light brown", "Soft mushroom brown"],
    patterns: ["Soft florals", "Watercolour dots", "Low-contrast cool stripes"],
    neutrals: ["Soft white", "Cool grey", "Powder blue"],
    occasions: [
      { label: "Business", suggestion: "Soft grey suit, powder blue shirt, lilac tie" },
      { label: "Casual", suggestion: "Lavender knit, light denim, grey sneakers" },
      { label: "Formal", suggestion: "Dusty blue dress with silver jewelry" },
    ],
  },
  true_summer: {
    contrastLevel: "medium",
    valueDepth: "medium",
    suits: [
      "Cool navy or slate blue suit",
      "Soft charcoal with cool undertone",
    ],
    shirtsAndBlouses: ["Cool white", "Soft raspberry", "Periwinkle", "Rose"],
    tiesAndScarves: ["Raspberry", "Periwinkle", "Cool plum"],
    casualWear: ["Soft blue polos", "Rose or raspberry tees", "Cool grey chinos"],
    dressesAndSkirts: ["Raspberry wrap dress", "Periwinkle fit-and-flare"],
    denim: ["Medium cool denim", "Cool grey or navy chinos"],
    outerwear: ["Cool navy peacoat", "Soft charcoal jacket"],
    shoesAndBags: ["Cool brown or navy leather", "Raspberry or plum accent"],
    makeup: {
      lips: ["Raspberry", "Cool rose", "Soft plum"],
      cheeks: ["Cool pink", "Soft raspberry"],
      eyes: ["Cool taupe", "Soft plum", "Navy liner"],
    },
    jewelry: ["Silver", "Platinum", "Rose quartz", "Soft sapphire"],
    hairColorHints: ["Cool ash brown", "Soft burgundy gloss", "Ash blonde highlights"],
    patterns: ["Cool florals", "Soft paisley in rose or blue", "Medium-contrast stripes"],
    neutrals: ["Cool white", "Cool navy", "Soft charcoal"],
    occasions: [
      { label: "Interview", suggestion: "Cool navy suit, white shirt, raspberry tie" },
      { label: "Weekend", suggestion: "Periwinkle shirt, medium denim, white sneakers" },
      { label: "Evening", suggestion: "Raspberry dress, silver accessories" },
    ],
  },
  soft_summer: {
    contrastLevel: "low",
    valueDepth: "medium",
    suits: [
      "Muted blue-grey or soft taupe suit",
      "Dove grey with blended, not sharp, contrast",
    ],
    shirtsAndBlouses: ["Soft white", "Dusty rose", "Mauve", "Muted blue"],
    tiesAndScarves: ["Dusty rose", "Mauve", "Soft blue-grey"],
    casualWear: ["Mauve knits", "Soft blue chambray", "Taupe chinos"],
    dressesAndSkirts: ["Dusty rose midi", "Mauve slip dress", "Soft blue shirt dress"],
    denim: ["Muted blue denim", "Taupe or soft grey trousers"],
    outerwear: ["Taupe coat", "Soft blue-grey jacket"],
    shoesAndBags: ["Taupe leather", "Muted rose or mauve bags"],
    makeup: {
      lips: ["Dusty rose", "Mauve", "Soft berry"],
      cheeks: ["Dusty pink", "Soft mauve"],
      eyes: ["Taupe", "Soft mauve", "Muted plum shadow"],
    },
    jewelry: ["Soft silver", "Antique rose gold", "Smoky quartz"],
    hairColorHints: ["Mushroom brown", "Soft ash tones", "Muted burgundy gloss"],
    patterns: ["Blended florals", "Soft abstract prints", "Low-contrast checks"],
    neutrals: ["Soft white", "Taupe", "Blue-grey"],
    occasions: [
      { label: "Office", suggestion: "Blue-grey suit, mauve blouse, taupe pumps" },
      { label: "Casual", suggestion: "Dusty rose knit, muted denim, taupe loafers" },
      { label: "Dinner", suggestion: "Mauve dress, soft silver jewelry" },
    ],
  },
  soft_autumn: {
    contrastLevel: "low",
    valueDepth: "medium",
    suits: [
      "Soft olive or warm taupe suit",
      "Muted camel with gentle, earthy contrast",
    ],
    shirtsAndBlouses: ["Ivory", "Soft peach", "Dusty coral", "Muted olive"],
    tiesAndScarves: ["Soft terracotta", "Muted olive", "Warm taupe"],
    casualWear: ["Olive knits", "Soft terracotta tees", "Warm taupe chinos"],
    dressesAndSkirts: ["Terracotta midi", "Soft olive wrap", "Muted coral dress"],
    denim: ["Muted medium denim", "Olive or taupe chinos"],
    outerwear: ["Camel coat", "Soft olive jacket"],
    shoesAndBags: ["Warm taupe", "Soft cognac", "Olive accent bags"],
    makeup: {
      lips: ["Terracotta", "Soft coral", "Warm nude"],
      cheeks: ["Soft terracotta", "Warm peach bronze"],
      eyes: ["Bronze", "Soft olive", "Warm taupe shadow"],
    },
    jewelry: ["Antique gold", "Warm bronze", "Amber", "Soft turquoise"],
    hairColorHints: ["Soft auburn", "Caramel brown", "Warm chestnut gloss"],
    patterns: ["Earthy florals", "Soft paisley", "Muted animal print"],
    neutrals: ["Ivory", "Warm taupe", "Soft olive"],
    occasions: [
      { label: "Work", suggestion: "Soft olive suit, ivory shirt, terracotta tie" },
      { label: "Weekend", suggestion: "Terracotta knit, taupe chinos, cognac boots" },
      { label: "Outdoor event", suggestion: "Muted coral dress, antique gold jewelry" },
    ],
  },
  true_autumn: {
    contrastLevel: "medium",
    valueDepth: "medium",
    suits: [
      "Rich brown, deep olive, or warm charcoal suit",
      "Burnt orange or rust blazer for statement looks",
    ],
    shirtsAndBlouses: ["Warm ivory", "Mustard", "Rust", "Deep teal"],
    tiesAndScarves: ["Rust", "Mustard", "Deep teal", "Burnt orange"],
    casualWear: ["Rust henleys", "Mustard knits", "Olive chinos"],
    dressesAndSkirts: ["Rust wrap dress", "Deep teal midi", "Mustard shirt dress"],
    denim: ["Dark warm denim", "Olive or brown chinos"],
    outerwear: ["Rich brown coat", "Deep olive parka"],
    shoesAndBags: ["Cognac", "Deep brown leather", "Rust or teal accent"],
    makeup: {
      lips: ["Rust", "Warm brick", "Deep coral"],
      cheeks: ["Warm bronze", "Terracotta blush"],
      eyes: ["Copper", "Deep olive", "Bronze shadow"],
    },
    jewelry: ["Yellow gold", "Copper", "Tiger eye", "Deep teal stones"],
    hairColorHints: ["Copper red", "Rich auburn", "Deep warm brown"],
    patterns: ["Autumn florals", "Warm plaids", "Ethnic warm prints"],
    neutrals: ["Warm ivory", "Camel", "Rich brown"],
    occasions: [
      { label: "Business", suggestion: "Deep olive suit, warm ivory shirt, rust tie" },
      { label: "Casual", suggestion: "Mustard knit, dark denim, cognac boots" },
      { label: "Fall wedding", suggestion: "Deep teal dress, gold accessories" },
    ],
  },
  deep_autumn: {
    contrastLevel: "medium",
    valueDepth: "deep",
    suits: [
      "Deep chocolate brown or forest green suit",
      "Warm charcoal with rich, saturated accents",
    ],
    shirtsAndBlouses: ["Warm cream", "Deep rust", "Forest green", "Burgundy"],
    tiesAndScarves: ["Deep rust", "Forest green", "Warm burgundy"],
    casualWear: ["Forest green knits", "Deep rust tees", "Dark olive chinos"],
    dressesAndSkirts: ["Burgundy midi", "Forest green wrap", "Deep rust dress"],
    denim: ["Dark indigo with warm cast", "Dark olive trousers"],
    outerwear: ["Deep brown coat", "Forest green jacket"],
    shoesAndBags: ["Dark cognac", "Deep brown", "Burgundy accent bags"],
    makeup: {
      lips: ["Deep brick", "Burgundy", "Warm plum"],
      cheeks: ["Deep terracotta", "Warm bronze"],
      eyes: ["Deep bronze", "Forest green liner", "Copper shadow"],
    },
    jewelry: ["Antique gold", "Deep amber", "Garnet", "Dark turquoise"],
    hairColorHints: ["Deep chestnut", "Dark auburn", "Espresso with copper lights"],
    patterns: ["Rich paisley", "Deep florals", "Warm geometric prints"],
    neutrals: ["Warm cream", "Deep brown", "Forest green"],
    occasions: [
      { label: "Formal", suggestion: "Deep brown suit, cream shirt, burgundy tie" },
      { label: "Casual", suggestion: "Forest green knit, dark denim, brown boots" },
      { label: "Evening", suggestion: "Burgundy dress, antique gold jewelry" },
    ],
  },
  deep_winter: {
    contrastLevel: "high",
    valueDepth: "deep",
    suits: [
      "True black or deep navy suit with crisp contrast",
      "Deep burgundy or emerald suit for formal events",
    ],
    shirtsAndBlouses: ["Pure white", "Deep fuchsia", "Emerald", "Icy pink"],
    tiesAndScarves: ["Deep burgundy", "Emerald", "Royal purple"],
    casualWear: ["Black knits", "Deep fuchsia tees", "Dark navy chinos"],
    dressesAndSkirts: ["Emerald gown", "Deep fuchsia dress", "Black sheath"],
    denim: ["Dark cool denim", "Black trousers"],
    outerwear: ["Black wool coat", "Deep navy peacoat"],
    shoesAndBags: ["Black leather", "Deep burgundy or emerald bags"],
    makeup: {
      lips: ["Deep fuchsia", "True red", "Berry"],
      cheeks: ["Cool rose", "Soft berry blush"],
      eyes: ["Charcoal", "Emerald liner", "Silver shadow"],
    },
    jewelry: ["Silver", "Platinum", "Emerald", "Deep sapphire"],
    hairColorHints: ["Blue-black", "Cool dark brown", "Platinum highlights if desired"],
    patterns: ["Bold geometric", "High-contrast stripes", "Jewel-tone florals"],
    neutrals: ["True black", "Pure white", "Deep navy"],
    occasions: [
      { label: "Black tie", suggestion: "Black suit, white shirt, emerald pocket square" },
      { label: "Business", suggestion: "Deep navy suit, white shirt, burgundy tie" },
      { label: "Party", suggestion: "Deep fuchsia dress, silver statement earrings" },
    ],
  },
  true_winter: {
    contrastLevel: "high",
    valueDepth: "medium",
    suits: [
      "Black or cool navy suit — sharp, clean lines",
      "Pure white suit for warm-climate formal (optional)",
    ],
    shirtsAndBlouses: ["Optic white", "True red", "Royal blue", "Hot pink"],
    tiesAndScarves: ["True red", "Royal blue", "Black and white contrast"],
    casualWear: ["Black and white combos", "Royal blue knits", "Crisp white shirts"],
    dressesAndSkirts: ["True red dress", "Royal blue fit-and-flare", "Black and white"],
    denim: ["Dark indigo denim", "Black jeans"],
    outerwear: ["Black coat", "Royal blue statement coat"],
    shoesAndBags: ["Black or white leather", "Red or royal blue accent"],
    makeup: {
      lips: ["True red", "Hot pink", "Cool berry"],
      cheeks: ["Cool pink", "Soft red"],
      eyes: ["Navy liner", "Silver shadow", "Charcoal smoky eye"],
    },
    jewelry: ["Silver", "Platinum", "Diamond or crystal", "Sapphire"],
    hairColorHints: ["Jet black", "Cool dark brown", "Ash highlights"],
    patterns: ["Bold stripes", "Color-block", "Graphic black and white"],
    neutrals: ["Optic white", "True black", "Cool navy"],
    occasions: [
      { label: "Interview", suggestion: "Black suit, white shirt, royal blue tie" },
      { label: "Casual", suggestion: "White shirt, dark denim, black sneakers" },
      { label: "Cocktail", suggestion: "True red dress, silver jewelry" },
    ],
  },
  bright_winter: {
    contrastLevel: "high",
    valueDepth: "medium",
    suits: [
      "Black suit with vivid accent (hot pink, electric blue)",
      "Cool navy with high-chroma pocket square",
    ],
    shirtsAndBlouses: ["Icy white", "Hot pink", "Electric blue", "Vivid violet"],
    tiesAndScarves: ["Hot pink", "Electric blue", "Vivid violet"],
    casualWear: ["Electric blue knits", "Hot pink accents on black base", "Icy white shirts"],
    dressesAndSkirts: ["Hot pink dress", "Electric blue slip", "Black with vivid belt"],
    denim: ["Dark cool denim", "Black jeans with vivid tops"],
    outerwear: ["Black coat with bright scarf", "Electric blue jacket"],
    shoesAndBags: ["Black or white base", "Hot pink or electric blue statement bag"],
    makeup: {
      lips: ["Hot pink", "Blue-red", "Fuchsia"],
      cheeks: ["Cool bright pink", "Soft fuchsia"],
      eyes: ["Vivid violet", "Electric blue liner", "Silver glitter accent"],
    },
    jewelry: ["Silver", "Platinum", "Vivid gemstone accents"],
    hairColorHints: ["Cool black", "Blue-black", "Vivid fashion colors if desired"],
    patterns: ["Bold color-block", "Neon-accent graphics", "High-contrast abstract"],
    neutrals: ["Icy white", "True black", "Cool charcoal"],
    occasions: [
      { label: "Business", suggestion: "Black suit, icy white shirt, electric blue tie" },
      { label: "Night out", suggestion: "Hot pink dress, silver statement jewelry" },
      { label: "Creative event", suggestion: "Color-block outfit in your vivid palette" },
    ],
  },
};
